version: 2
jobs:
  build:
    working_directory: ~/smswebapp
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: mysecretpass
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
            - ".tox"
      - run:
          environment:
              DJANGO_DB_ENGINE: django.db.backends.postgresql
              DJANGO_DB_NAME: circle_test
              DJANGO_DB_HOST: localhost
              DJANGO_DB_USER: root
              DJANGO_DB_PASSWORD: mysecretpass
          command: |
            . venv/bin/activate
            tox
      # FIXME: we currently do not generate any test reports
      - store_artifacts:
          path: test-reports/
          destination: tr1

